#!/usr/bin/env bash
#


# close system preferences to keep it from overriding stuff
osascript -e 'tell application "System Preferences" to quit'

# Dock settings
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock "orientation" -string "right"
defaults write com.apple.dock "tilesize" -int "45"

# translucent dock icons for hidden apps
defaults write com.apple.dock showhidden -bool true

# hide recent apps
defaults write com.apple.dock show-recents -bool false


# enable keyboard press and hold popup
defaults write -g ApplePressAndHoldEnabled -bool true

# fast keyboard repeat rate
defaults write -g KeyRepeat -int 2
defaults write -g InitialKeyRepeat -int 15

# Remap caps-lock to escape
hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000039,"HIDKeyboardModifierMappingDst":0x7000000E0}]}'

# add the click anywhere to move window feature (https://mmazzarolo.com/blog/2022-04-16-drag-window-by-clicking-anywhere-on-macos/)
defaults write -g NSWindowShouldDragOnGesture -bool true


# disable text correction
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
defaults write -g NSAutomaticCapitalizationEnabled -bool false

# natural scroll direction
defaults write -g com.apple.swipescrolldirection -bool true
defaults write NSGlobalDomain com.apple.mouse.scddaling -float "3.0"
defaults write NSGlobalDomain com.apple.trackpad.scaling -int 5
defaults write -g com.apple.mouse.scaling  9.0


# expand print panel by default
defaults write -g PMPrintingExpandedStateForPrint -bool true
defaults write -g PMPrintingExpandedStateForPrint2 -bool true

# expand save panel by default
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true

# show all file extensions
defaults write -g AppleShowAllExtensions -bool true

# disable warning when changing file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# show all files
defaults write com.apple.finder AppleShowAllFiles -bool true



# finder shortcuts
defaults write com.apple.finder NSUserKeyEquivalents -dict-add "New Terminal at Folder" "^i"



### Mission Control
# defaults write com.apple.dock mcx-expose-disabled -bool true # (to disable it)
# defaults delete com.apple.dock mcx-expose-disabled # (to re-enable it)

# disable recent used spaces re-ordering
defaults write com.apple.dock mru-spaces -bool false

# disable apple's font smoothing, such that the OS doesn't modify the pixle outputs for text
defaults -currentHost write -g AppleFontSmoothing -int 0

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,nvim,tmux,zsh,hammerspoon"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

# Ensure stow is installed
if ! command -v stow &> /dev/null; then
    echo "stow could not be found, please install it first"
    exit 1
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install

killall Dock
killall Finder

read -p "




Press any key to continue " -n1 -s # this is complicated to set via script: https://apple.stackexchange.com/questions/201816/how-do-i-change-mission-control-shortcuts-from-the-command-line
echo ""
echo "Execution Complete."
echo ""
echo "Please reboot your Mac to complete the changes."
# prompt for reboot
