#!/usr/bin/env bash

# close system preferences to keep it from overriding stuff
osascript -e 'tell application "System Preferences" to quit'

# automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# translucent dock icons for hidden apps
defaults write com.apple.dock showhidden -bool true

# hide recent apps
defaults write com.apple.dock show-recents -bool false

# set the icon size of Dock items
defaults write com.apple.dock tilesize -int 50

# enable keyboard press and hold popup
defaults write -g ApplePressAndHoldEnabled -bool true

# fast keyboard repeat rate
defaults write -g KeyRepeat -int 2
defaults write -g InitialKeyRepeat -int 15

# disable text correction
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
defaults write -g NSAutomaticCapitalizationEnabled -bool false

# natural scroll direction
defaults write -g com.apple.swipescrolldirection -bool true

# expand print panel by default
defaults write -g PMPrintingExpandedStateForPrint -bool true
defaults write -g PMPrintingExpandedStateForPrint2 -bool true

# expand save panel by default
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true

# show all file extensions
defaults write -g AppleShowAllExtensions -bool true

# disable warning when changing file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# show all files
defaults write com.apple.finder AppleShowAllFiles -bool true



# finder shortcuts
defaults write com.apple.finder NSUserKeyEquivalents -dict-add "New Terminal at Folder" "^i"



### Mission Control
# defaults write com.apple.dock mcx-expose-disabled -bool true # (to disable it)
# defaults delete com.apple.dock mcx-expose-disabled # (to re-enable it)

# disable recent used spaces re-ordering
defaults write com.apple.dock mru-spaces -bool false


killall Dock
killall Finder

echo "Please manually change the required setting in the System Preferences app."
echo "Once you have made the change, press any key to continue."
echo ""
echo ""
read -p "Go to keyboard shortcuts and configure 

Move left a space: ⌃⇧H
Move right a space: ⌃⇧L 

Application Windows: ⌃⇧J
Mission Control: ⌃⇧K


Press any key to continue " -n1 -s # this is complicated to set via script: https://apple.stackexchange.com/questions/201816/how-do-i-change-mission-control-shortcuts-from-the-command-line
echo ""
echo "Execution Complete."
